name: Build

#  This workflow is the Provider's CI build that will run on every commit for the provider codebase

on:
  push:
  workflow_dispatch:

env:
  # PACT_BROKER_BASE_URL: ${{ vars.PACT_BROKER_BASE_URL }}
  # PACT_BROKER_USERNAME: ${{ vars.PACT_BROKER_USERNAME }}
  # PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
  # GITHUB_REF: ${{ github.ref }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref_name }}
  ENVIRONMENT: production
  PACT_CLI: docker run
    --rm -v ${PWD}:${PWD}
    -e PACT_BROKER_BASE_URL=${{ vars.PACT_BROKER_BASE_URL }}
    -e PACT_BROKER_USERNAME=${{ vars.PACT_BROKER_USERNAME }}
    -e PACT_BROKER_PASSWORD=${{ secrets.PACT_BROKER_PASSWORD }}
    pactfoundation/pact-cli:latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: docker pull pactfoundation/pact-cli:latest

      - name: Can I deploy? (valida todos los providers)
        run: |
          for provider in pactflow-example-provider
          do
            ${{ env.PACT_CLI }} broker can-i-deploy \
              --pacticipant $provider \
              --version ${{ env.GIT_COMMIT }} \
              --to-environment ${{ env.ENVIRONMENT }} \
              --retry-while-unknown 30 \
              --retry-interval 10
          done

  # Only deploy from master
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: can-i-deploy
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: docker pull pactfoundation/pact-cli:latest
  #     - name: Deploy
  #       run: GIT_BRANCH=${GITHUB_REF:11} make deploy
  #       if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/test'
